version: "3.9"

services:
  snippets:
    build: ./
    container_name: snippets
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - snippets:/usr/src/snippets
      - /usr/src/snippets/node_modules
      - /usr/src/snippets/.next
    depends_on:
      - snippets_db

  snippets_db:
    image: postgres
    container_name: snippets_db
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
    volumes:
      - snippets_db:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  snippets:
  snippets_db:
