import Head from "next/head"

import { Heading, Body, Button } from "@components"

const Home = () => {
  return (
    <div>
      <Head>
        <title>Anggans</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="absolute top-1/2 -translate-y-1/2">
        <Heading
          weight="bold"
          variant="h1"
          size="text-[36px] tablet:text-[48px]"
          className="dark:text-white "
        >
          Hi! I&apos;m{" "}
          <span className="selectable dark:text-blue-500">Angga</span>
        </Heading>
        <Body
          variant="b2"
          size="text-[16px] tablet:text-[20px]"
          className="tablet:mt-4 dark:text-white mb-8"
        >
          Just a guy who&apos;s curious about tech
        </Body>
        <div className="flex flex-wrap gap-4">
          <Button padding="p-4" href="/profile">
            <Body variant="b2" size="text-[16px] tablet:text-[20px]">
              More about me
            </Body>
          </Button>
          <Button padding="p-4" href="/posts">
            <Body variant="b2" size="text-[16px] tablet:text-[20px]">
              View my posts
            </Body>
          </Button>
        </div>
      </div>
    </div>
  )
}

export default Home
