import Head from "next/head"
import Image from "next/image"

import { Heading, Body, Button } from "@components"

import ProfileImage from "@images/profile.png"

const Home = () => {
  return (
    <div className="relative w-full mb-8">
      <Head>
        <title>Angga</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="flex items-start justify-evenly desktop:justify-between desktop:flex-row flex-col w-full h-[75vh]">
        <div className="desktop:my-auto my-0 desktop:w-1/2 w-full desktop:order-1 order-2">
          <Heading
            weight="bold"
            variant="h1"
            size="text-[36px] tablet:text-[48px] extraWide:text-[60px]"
            className="dark:text-white "
          >
            Hi! I&apos;m{" "}
            <span className="selectable dark:text-blue-500">Angga</span>
          </Heading>
          <Body
            variant="b2"
            size="text-[16px] tablet:text-[20px] extraWide:text-[28px]"
            className="tablet:mt-4 dark:text-white mb-8"
          >
            Just a guy who&apos;s curious about tech
          </Body>
          <div className="flex flex-wrap gap-4">
            <Button padding="p-4" href="/profile">
              <Body variant="b2" size="text-[16px] tablet:text-[20px]">
                More about me
              </Body>
            </Button>
            <Button padding="p-4" href="/posts">
              <Body variant="b2" size="text-[16px] tablet:text-[20px]">
                View my posts
              </Body>
            </Button>
          </div>
        </div>
        <div className="mx-auto desktop:m-auto desktop:w-2/5 tablet:w-3/4 w-4/5 h-full relative aspect-square desktop:order-2 order-1">
          <Image
            src={ProfileImage}
            alt="Profile Image"
            layout="fill"
            objectFit="contain"
            quality={100}
          />
        </div>
      </div>
    </div>
  )
}

export default Home
